services:
  - type: web
    name: estoque-backend
    env: python
    buildCommand: ""
    startCommand: "python app.py"
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
